import sqlite3
conn=sqlite3.connect("details.db")
# conn.execute("create table IF NOT EXISTS newsite(siteid INTEGER PRIMARY KEY AUTOINCREMENT,sitename text UNIQUE,sitestart text,sitedept number,sitemanager TEXT,added TEXT,updated TEXT,activated TEXT)")
# conn.commit()
conn.execute("create table IF NOT EXISTS newparty(partyid INTEGER PRIMARY KEY AUTOINCREMENT,partyname text,paddress text,gstin text,pmobile number,email text,rent number,leaseexpiry TEXT,added TEXT,updated TEXT,activated TEXT)")
conn.commit()
# conn.execute("create table IF NOT EXISTS newmaterial(matid INTEGER PRIMARY KEY AUTOINCREMENT,matname text UNIQUE,mattype TEXT,matdescrip text,matunit number,charge INTEGER Default(0),added TEXT,updated TEXT,activated TEXT)")
# conn.commit()
# conn.execute("create table if not EXISTS purchase(pid INTEGER,date text,siteid text,partyid text,transport text,material text,price number,quantity text,uom text,amount number,paid number,balance number,cdebit number Default(0),ccredit number Default(0),chqdebit number Default(0),chqcredit number Default(0),chqnumber text,remark text,chqdate TEXT,added TEXT,updated TEXT,transtype TEXT)")
# conn.commit()
# conn.execute("create table if not EXISTS credit(pid INTEGER,siteid text,partyid text,cash number Default(0),cheque number Default(0),chqnumber text,remark text,chqdate TEXT,added TEXT,updated TEXT,transtype TEXT)")
# conn.commit()
# conn.execute("create table if not EXISTS receiverent(pid INTEGER,partyid text,rent number Default(0),chqnumber text,remark text,chqdate TEXT,added TEXT,updated TEXT)")
# conn.commit()
# conn.execute("create table IF NOT EXISTS firminfo(firm text,city text,state TEXT,landmark TEXT,mob1 TEXT,mob2 TEXT,pincode text,email text,website text)")
# conn.commit()
# conn.execute("create table IF NOT EXISTS logindet(user text,pass text,date text)")
# conn.commit()
# conn.execute("create table IF NOT EXISTS matunit(unit text, added text)")
# # conn.commit()
# conn.execute("create table IF NOT EXISTS extrascriptcheck(extracheck TEXT Default(0))")
# conn.commit()
conn.execute("create table IF NOT EXISTS rentledger(id INTEGER PRIMARY KEY AUTOINCREMENT,partyid TEXT,rentreceive number,rentMonth text,chqdate TEXT,chqnumber TEXT,remark text,rentreceivedate text,added text,updated text)")
conn.commit()
conn.execute("create table IF NOT EXISTS loginhistory(lastlogin TEXT,user text,date text)")
conn.commit()
# conn.execute("create table IF NOT EXISTS registration(country TEXT,mac TEXT,voip TEXT,connection number,reverse number,email text,updated TEXT,updatedate TEXT,uid TEXT,status TEXT,option1 TEXT,option2 TEXT)")
conn.execute("create table IF NOT EXISTS loginusers(user TEXT,pass TEXT,added TEXT,updated TEXT)")
conn.commit()
# conn.execute("create table IF NOT EXISTS employee(eid INTEGER PRIMARY KEY AUTOINCREMENT,name text,father text,address text,category text,mob1 text,mob2 text,working text,payout text,wage INTEGER,status text)")
# conn.commit()
# conn.execute("create table IF NOT EXISTS salary(pid text,date text,employee text,month text,days text,hours text,year text,category text,cash text,cheque text,chqnumber text,total text,remark text,salary text,absent text)")
# conn.commit()
# conn.execute("create table if not EXISTS deletedrecord(pid INTEGER PRIMARY KEY AUTOINCREMENT,date text,deleteddate text,sitename text,party text,partytype text,material text,price number,quantity text,uom text,amount number,paid number,balance number,deposit number,camount number,camount1 number,chqamount number,chqamount1 number,chqnumber text,remark text)")
# conn.commit()

conn.close()