# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'party.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddParty(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1594, 552)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("QFrame{border:1px solid black;\n"
"background-color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_2.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"border-radius:8;\n"
"border:none;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(14, 14, 14, 14)
        self.gridLayout_3.setVerticalSpacing(12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_4.setStyleSheet("background-color: rgb(254, 255, 193);\n"
"font: 10pt \"Rockwell\";\n"
"color: rgb(0, 85, 127);\n"
"padding-left:10px;\n"
"")
        self.lineEdit_4.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 1, 1, 1, 2)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_6.setStyleSheet("background-color: rgb(254, 255, 193);\n"
"font: 10pt \"Rockwell\";\n"
"color: rgb(0, 85, 127);\n"
"padding-left:10px;\n"
"")
        self.lineEdit_6.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setClearButtonEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_3.addWidget(self.lineEdit_6, 4, 1, 1, 2)
        self.label_37 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Reference Sans Serif\";\n"
"border:none;")
        self.label_37.setFrameShape(QtWidgets.QFrame.Box)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_3.addWidget(self.label_37, 2, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Reference Sans Serif\";\n"
"border:none;")
        self.label_36.setFrameShape(QtWidgets.QFrame.Box)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 5, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 130, 80);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Arial Black\";\n"
"border:2px solid grey;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(56, 56, 56);\n"
"border:2px solid white;}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 8, 1, 1, 2)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_9.setStyleSheet("background-color: rgb(254, 255, 193);\n"
"font: 10pt \"Rockwell\";\n"
"color: rgb(0, 85, 127);\n"
"padding-left:10px;\n"
"")
        self.lineEdit_9.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
        self.lineEdit_9.setText("")
        self.lineEdit_9.setClearButtonEnabled(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_3.addWidget(self.lineEdit_9, 3, 1, 1, 2)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_5.setStyleSheet("background-color: rgb(254, 255, 193);\n"
"font: 10pt \"Rockwell\";\n"
"color: rgb(0, 85, 127);\n"
"padding-left:10px;\n"
"")
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 2, 1, 1, 2)
        self.label_35 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Reference Sans Serif\";\n"
"border:none;")
        self.label_35.setFrameShape(QtWidgets.QFrame.Box)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 3, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Reference Sans Serif\";\n"
"border:none;")
        self.label_39.setFrameShape(QtWidgets.QFrame.Box)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 4, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Reference Sans Serif\";\n"
"border:none;")
        self.label_34.setFrameShape(QtWidgets.QFrame.Box)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_2.setStyleSheet("background-color: rgb(254, 255, 193);\n"
"font: 10pt \"Rockwell\";\n"
"color: rgb(0, 85, 127);\n"
"padding-left:10px;\n"
"")
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 0, 1, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_3.setStyleSheet("background-color: rgb(254, 255, 193);\n"
"font: 10pt \"Rockwell\";\n"
"color: rgb(0, 85, 127);\n"
"padding-left:10px;\n"
"")
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 5, 1, 1, 2)
        self.dateEdit_6 = QtWidgets.QDateEdit(self.frame_2)
        self.dateEdit_6.setMinimumSize(QtCore.QSize(0, 40))
        self.dateEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(0, 85, 127);")
        self.dateEdit_6.setCalendarPopup(True)
        self.dateEdit_6.setObjectName("dateEdit_6")
        self.gridLayout_3.addWidget(self.dateEdit_6, 7, 1, 1, 2)
        self.label_33 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Reference Sans Serif\";\n"
"border:none;")
        self.label_33.setFrameShape(QtWidgets.QFrame.Box)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Reference Sans Serif\";\n"
"border:none;")
        self.label_38.setFrameShape(QtWidgets.QFrame.Box)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 7, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_2.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 130, 80);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Arial Black\";\n"
"border:2px solid grey;}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 85, 127);\n"
"border:2px solid white;}")
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("border:none;\n"
"\n"
"color: rgb(0, 85, 127);\n"
"font: 87 16pt \"Arial Black\";\n"
"padding-left:20;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setMinimumSize(QtCore.QSize(700, 0))
        self.tableWidget.setStyleSheet("border:1px solid grey;\n"
"alternate-background-color: rgb(231, 231, 231);\n"
"background-color: rgb(255, 255, 255);")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(2)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(37)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.gridLayout_2.addWidget(self.tableWidget, 1, 1, 1, 3)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(400, 45))
        self.lineEdit_14.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_14.setStyleSheet("font: 75 11pt \"Tahoma\";\n"
"background-color: rgb(0, 85, 127);\n"
"color: white;\n"
"border:2px solid grey;\n"
"border-radius:0;")
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_14.setClearButtonEnabled(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_2.addWidget(self.lineEdit_14, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_2, self.lineEdit_4)
        Dialog.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        Dialog.setTabOrder(self.lineEdit_5, self.lineEdit_9)
        Dialog.setTabOrder(self.lineEdit_9, self.lineEdit_6)
        Dialog.setTabOrder(self.lineEdit_6, self.lineEdit_3)
        Dialog.setTabOrder(self.lineEdit_3, self.dateEdit_6)
        Dialog.setTabOrder(self.dateEdit_6, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.pushButton_2)
        Dialog.setTabOrder(self.pushButton_2, self.lineEdit_14)
        Dialog.setTabOrder(self.lineEdit_14, self.tableWidget)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_37.setText(_translate("Dialog", "MOBILE NUMBER"))
        self.label_36.setText(_translate("Dialog", "RENT AMOUNT"))
        self.pushButton.setText(_translate("Dialog", "CREATE PARTY"))
        self.label_35.setText(_translate("Dialog", "EMAIL ID"))
        self.label_39.setText(_translate("Dialog", "GSTIN"))
        self.label_34.setText(_translate("Dialog", "ADDRESS"))
        self.lineEdit_3.setText(_translate("Dialog", "0"))
        self.label_33.setText(_translate("Dialog", "PARTY NAME"))
        self.label_38.setText(_translate("Dialog", "LEASE EXPIRY"))
        self.pushButton_2.setText(_translate("Dialog", "X"))
        self.label.setText(_translate("Dialog", "ADD PARTY / TENANT"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "PARTY ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "PARTY"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "MOB."))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "EMAIL ID"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "ADDRESS"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "RENT AMT."))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "LEASE EXPIRY"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "EDIT"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "DELETE"))
        self.lineEdit_14.setPlaceholderText(_translate("Dialog", "Search Here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_AddParty()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
