# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'receive_rent.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReceiveRent(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 705)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setAutoFillBackground(False)
        self.frame_3.setStyleSheet("QFrame{background-color: rgb(255, 255, 255);\n"
"border:1px solid black;}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setStyleSheet("background-color: rgb(0, 58, 85);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setMinimumSize(QtCore.QSize(170, 35))
        self.label_5.setStyleSheet("background-color: rgb(52, 167, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Tw Cen MT Condensed Extra Bold\";\n"
"")
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.frame)
        self.label_38.setMinimumSize(QtCore.QSize(0, 35))
        self.label_38.setStyleSheet("background-color: rgb(52, 167, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Tw Cen MT Condensed Extra Bold\";\n"
"")
        self.label_38.setFrameShape(QtWidgets.QFrame.Box)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 3, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_3.setStyleSheet("QPushButton{background-color: rgb(85, 170, 255);\n"
"    \n"
"    background-color: rgb(255, 0, 127);\n"
"border-radius:8px;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"\n"
"\n"
"\n"
"font: 87 10pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"border-radius5px;}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 4, 3, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("background-color: rgb(212, 212, 212);\n"
"PADDING:10;\n"
"margin:0;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setVerticalSpacing(25)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_11.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Rod\";\n"
"padding:0;\n"
"padding-right:10;\n"
"margin:0;\n"
"")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_11.setClearButtonEnabled(False)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_4.addWidget(self.lineEdit_11, 0, 2, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.frame_2)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.dateEdit.setStyleSheet("selection-background-color: rgb(170, 0, 127);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0,0,0);\n"
"selection-color: rgb(255, 255, 255);")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_4.addWidget(self.dateEdit, 4, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.frame_2)
        self.label_39.setMinimumSize(QtCore.QSize(0, 35))
        self.label_39.setStyleSheet("background-color: rgb(52, 167, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 13pt \"Tw Cen MT Condensed Extra Bold\";\n"
"padding:0;\n"
"padding-left:10;\n"
"padding-right:10;\n"
"margin:0;\n"
"")
        self.label_39.setFrameShape(QtWidgets.QFrame.Box)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 4, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.frame_2)
        self.label_40.setMinimumSize(QtCore.QSize(0, 35))
        self.label_40.setStyleSheet("background-color: rgb(52, 167, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 13pt \"Tw Cen MT Condensed Extra Bold\";\n"
"padding:0;\n"
"padding-left:10;\n"
"padding-right:10;\n"
"margin:0;\n"
"")
        self.label_40.setFrameShape(QtWidgets.QFrame.Box)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 2, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_2)
        self.label_34.setMinimumSize(QtCore.QSize(0, 35))
        self.label_34.setStyleSheet("background-color: rgb(52, 167, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 13pt \"Tw Cen MT Condensed Extra Bold\";\n"
"padding:0;\n"
"padding-left:10;\n"
"padding-right:10;\n"
"margin:0;\n"
"")
        self.label_34.setFrameShape(QtWidgets.QFrame.Box)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 3, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_10.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Rod\";\n"
"padding:0;\n"
"padding-right:10;\n"
"margin:0;\n"
"")
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_4.addWidget(self.lineEdit_10, 3, 2, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame_2)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.dateTimeEdit.setStyleSheet("selection-background-color: rgb(170, 0, 127);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0,0,0);\n"
"selection-color: rgb(255, 255, 255);")
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_4.addWidget(self.dateTimeEdit, 2, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_2)
        self.label_37.setMinimumSize(QtCore.QSize(0, 35))
        self.label_37.setStyleSheet("background-color: rgb(52, 167, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 13pt \"Tw Cen MT Condensed Extra Bold\";\n"
"padding:0;\n"
"padding-left:10;\n"
"padding-right:10;\n"
"margin:0;\n"
"")
        self.label_37.setFrameShape(QtWidgets.QFrame.Box)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 0, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.frame_2)
        self.label_35.setMinimumSize(QtCore.QSize(0, 35))
        self.label_35.setStyleSheet("background-color: rgb(52, 167, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 13pt \"Tw Cen MT Condensed Extra Bold\";\n"
"padding:0;\n"
"padding-left:10;\n"
"padding-right:10;\n"
"margin:0;\n"
"")
        self.label_35.setFrameShape(QtWidgets.QFrame.Box)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 5, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_13.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Rod\";\n"
"padding:0;\n"
"padding-right:10;\n"
"margin:0;")
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_4.addWidget(self.lineEdit_13, 5, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.frame_2)
        self.label_41.setMinimumSize(QtCore.QSize(0, 35))
        self.label_41.setStyleSheet("background-color: rgb(52, 167, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 13pt \"Tw Cen MT Condensed Extra Bold\";\n"
"padding:0;\n"
"padding-left:10;\n"
"padding-right:10;\n"
"margin:0;\n"
"")
        self.label_41.setFrameShape(QtWidgets.QFrame.Box)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 127);\n"
"font: 75 12pt \"Arial Narrow\";\n"
"selection-background-color: rgb(85, 85, 127);\n"
"selection-color: rgb(255, 255, 255);")
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_4.addWidget(self.comboBox, 1, 2, 1, 1)
        self.lineEdit_11.raise_()
        self.lineEdit_10.raise_()
        self.label_34.raise_()
        self.label_37.raise_()
        self.label_35.raise_()
        self.lineEdit_13.raise_()
        self.label_39.raise_()
        self.dateEdit.raise_()
        self.dateTimeEdit.raise_()
        self.label_40.raise_()
        self.label_41.raise_()
        self.comboBox.raise_()
        self.gridLayout_3.addWidget(self.frame_2, 2, 0, 1, 4)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_9.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_3.addWidget(self.lineEdit_9, 3, 1, 1, 3)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_2.setStyleSheet("selection-background-color: rgb(255, 170, 127);\n"
"font: 75 11pt \"Verdana\";\n"
"background-color: rgb(225, 225, 225);\n"
"selection-color: rgb(15, 15, 15);\n"
"padding-left:10;")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setDuplicatesEnabled(False)
        self.comboBox_2.setFrame(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_3.addWidget(self.comboBox_2, 1, 1, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 127);\n"
"    \n"
"border-radius:8px;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"\n"
"\n"
"\n"
"font: 87 10pt \"Arial Black\";\n"
"    color: grey;\n"
"border-radius5px;}\n"
"QPushButton:hover{\n"
"color:white;\n"
"    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 4, 1, 1, 2)
        self.pushButton.raise_()
        self.frame_2.raise_()
        self.lineEdit_9.raise_()
        self.comboBox_2.raise_()
        self.label_38.raise_()
        self.label_5.raise_()
        self.pushButton_3.raise_()
        self.gridLayout_2.addWidget(self.frame, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_4.setStyleSheet("background-color: rgb(84, 84, 84);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setStyleSheet("border:none;\n"
"\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"font: 75 17pt \"Tw Cen MT Condensed Extra Bold\";\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"color: rgb(255,255,255);\n"
"font: 75 12pt \"Tw Cen MT Condensed Extra Bold\";\n"
"border:none;\n"
"")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setMinimumSize(QtCore.QSize(90, 0))
        self.label_9.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"color: rgb(255,255,255);\n"
"font: 75 12pt \"Tw Cen MT Condensed Extra Bold\";\n"
"")
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_2.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_2.setStyleSheet("\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 85, 127);\n"
"}")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../contra_new/Icons/closeicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout_2.addWidget(self.frame_4, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "TENANT / PARTY"))
        self.label_38.setText(_translate("Dialog", "REMARK"))
        self.pushButton_3.setText(_translate("Dialog", "  Delete"))
        self.lineEdit_11.setPlaceholderText(_translate("Dialog", "0"))
        self.label_39.setText(_translate("Dialog", "CHEQUE DATE"))
        self.label_40.setText(_translate("Dialog", "RENT RECEIVE DATE"))
        self.label_34.setText(_translate("Dialog", "CHEQUE NO."))
        self.label_37.setText(_translate("Dialog", "RENT AMOUNT (RS.)"))
        self.label_35.setText(_translate("Dialog", "TOTAL"))
        self.label_41.setText(_translate("Dialog", "RENT FOR MONTH"))
        self.comboBox.setItemText(0, _translate("Dialog", "JANUARY"))
        self.comboBox.setItemText(1, _translate("Dialog", "FEBRUARY"))
        self.comboBox.setItemText(2, _translate("Dialog", "MARCH"))
        self.comboBox.setItemText(3, _translate("Dialog", "APRIL"))
        self.comboBox.setItemText(4, _translate("Dialog", "MAY"))
        self.comboBox.setItemText(5, _translate("Dialog", "JUNE"))
        self.comboBox.setItemText(6, _translate("Dialog", "JULY"))
        self.comboBox.setItemText(7, _translate("Dialog", "AUGUST"))
        self.comboBox.setItemText(8, _translate("Dialog", "SEPTEMBER"))
        self.comboBox.setItemText(9, _translate("Dialog", "OCTOBER"))
        self.comboBox.setItemText(10, _translate("Dialog", "NOVEMBER"))
        self.comboBox.setItemText(11, _translate("Dialog", "DECEMBER"))
        self.pushButton.setText(_translate("Dialog", "Receive Rent"))
        self.label.setText(_translate("Dialog", "Receive Rent"))
        self.label_4.setText(_translate("Dialog", "Receipt No.:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_ReceiveRent()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
